name: Pull electricity prices
on:
  schedule:
    - cron: "15 12 * * *"

jobs:
  pull-electricity-prices:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run script to pull electricity prices
        run: |
          tomorrow=$(date --date="tomorrow" -Idate); echo "[
            $(curl -s https://www.vattenfall.se/api/price/spot/pricearea/$tomorrow/$tomorrow/SN1),
            $(curl -s https://www.vattenfall.se/api/price/spot/pricearea/$tomorrow/$tomorrow/SN2),
            $(curl -s https://www.vattenfall.se/api/price/spot/pricearea/$tomorrow/$tomorrow/SN3),
            $(curl -s https://www.vattenfall.se/api/price/spot/pricearea/$tomorrow/$tomorrow/SN4)
          ]" | jq -r '. | transpose | map({timestamp: .[0].TimeStamp, SE1: .[0].Value, SE2: .[1].Value, SE3: .[2].Value, SE4: .[3].Value}) | (.[0] | keys_unsorted) as $keys | map([.[ $keys[] ]])[] | @csv' >> elpriser.csv

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Pull electricity prices

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - uses: actions/cache@v2
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install datasette datasette-publish-vercel sqlite-utils

      - name: Create database
        run: sqlite-utils insert elpriser.db elpriser elpriser.csv --csv --detect-types

      - name: Deploy Datasette using Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |-
          datasette publish vercel elpriser.db \
            --token $VERCEL_TOKEN \
            --project elpriser \
            --public
