name: Pull electricity prices
on:
  schedule:
    - cron: "15 13 * * *"
  workflow_dispatch:

jobs:
  pull-electricity-prices:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run script to pull electricity prices
        run: |
          tomorrow=$(date --date="tomorrow" -Idate)
          SE1=$(curl https://www.vattenfall.se/api/price/spot/pricearea/$tomorrow/$tomorrow/SN1)
          SE2=$(curl https://www.vattenfall.se/api/price/spot/pricearea/$tomorrow/$tomorrow/SN2)
          SE3=$(curl https://www.vattenfall.se/api/price/spot/pricearea/$tomorrow/$tomorrow/SN3)
          SE4=$(curl https://www.vattenfall.se/api/price/spot/pricearea/$tomorrow/$tomorrow/SN4)

          csv=$(echo "[]" | jq -r --argjson SE1 $SE1 --argjson SE2 $SE2 --argjson SE3 $SE3 --argjson SE4 $SE4 \
            '[$SE1, $SE2, $SE3, $SE4] | transpose | map({timestamp: .[0].TimeStamp, SE1: .[0].Value, SE2: .[1].Value, SE3: .[2].Value, SE4: .[3].Value}) | (.[0] | keys_unsorted) as $keys | map([.[ $keys[] ]])[] | @csv')
          echo "$csv" | grep -P '"\d{4}\-\d{2}\-\d{2}T00:00:00"(,\d+(\.\d+)?){4}'
          echo "$csv" >> elpriser.csv

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Pull electricity prices
